MarineDataSheet/Controllers/AllUsersController.cs
using MarineDataSheet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;

namespace MarineDataSheet.Controllers
{
    public class AllUsersController : Controller
    {
        // GET: AllUsers
        public ActionResult Users()
        {
            return View();
        }

        public ActionResult LoadUsersData()
        {
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                var rolesData = ShowallUsers(sortColumn, sortColumnDir, searchValue);
                recordsTotal = rolesData.Count();
                var data = rolesData.Skip(skip).Take(pageSize).ToList();

                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }

        public IQueryable<RegistrationViewSummaryModel> ShowallUsers(string sortColumn, string sortColumnDir, string Search)
        {
            var _context = new MarineDataEntities();

            var IQueryabletimesheet = (from registration in _context.Registrations
                                       join AssignedRoles in _context.AssignedRoles on registration.RegistrationID equals AssignedRoles.RegistrationID
                                       join AssignedRolesAdmin in _context.Registrations on AssignedRoles.AssignToAdmin equals AssignedRolesAdmin.RegistrationID
                                       where registration.RoleID == 2
                                       select new RegistrationViewSummaryModel
                                       {
                                           Name = registration.Name,
                                           AssignToAdmin = string.IsNullOrEmpty(AssignedRolesAdmin.Name) ? "*Not Assigned*" : AssignedRolesAdmin.Name.ToUpper(),
                                           RegistrationID = registration.RegistrationID,
                                           EmailID = registration.EmailID,
                                           Mobileno = registration.Mobileno,
                                           Username = registration.Username
                                       });

            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
            {
                IQueryabletimesheet = IQueryabletimesheet.OrderBy(sortColumn + " " + sortColumnDir);
            }
            if (!string.IsNullOrEmpty(Search))
            {
                IQueryabletimesheet = IQueryabletimesheet.Where(m => m.Name == Search);
            }

            return IQueryabletimesheet;

        }

        public ActionResult UserDetails(int? RegistrationID)
        {
            var _context = new MarineDataEntities();
            try
            {
                if (RegistrationID == null)
                {

                }
                var userDetailsResponse = from s in _context.Registrations where s.RoleID == 2 && s.RegistrationID == RegistrationID select s;
                return PartialView("_UserDetails", userDetailsResponse.FirstOrDefault());
            }
            catch (Exception)
            {
                throw;
            }
        }

        public ActionResult Admin()
        {
            return View();
        }


        public ActionResult LoadAdminsData()
        {
            try
            {
                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;

                int recordsTotal = 0;

                var rolesData = ShowallAdmin(sortColumn, sortColumnDir, searchValue);
                recordsTotal = rolesData.Count();
                var data = rolesData.Skip(skip).Take(pageSize).ToList();

                return Json(new { draw = draw, recordsFiltered = recordsTotal, recordsTotal = recordsTotal, data = data });
            }
            catch (Exception)
            {
                throw;
            }
        }
        public IQueryable<RegistrationViewSummaryModel> ShowallAdmin(string sortColumn, string sortColumnDir, string Search)
        {
            var _context = new MarineDataEntities();

            var IQueryabletimesheet = (from registration in _context.Registrations
                                       where registration.RoleID == 1
                                       select new RegistrationViewSummaryModel
                                       {
                                           Name = registration.Name,
                                           RegistrationID = registration.RegistrationID,
                                           EmailID = registration.EmailID,
                                           Mobileno = registration.Mobileno,
                                           Username = registration.Username
                                       });

            if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
            {
                IQueryabletimesheet = IQueryabletimesheet.OrderBy(sortColumn + " " + sortColumnDir);
            }
            if (!string.IsNullOrEmpty(Search))
            {
                IQueryabletimesheet = IQueryabletimesheet.Where(m => m.Name == Search);
            }

            return IQueryabletimesheet;

        }

        public ActionResult AdminDetails(int? RegistrationID)
        {
            var _context = new MarineDataEntities();
            try
            {
                if (RegistrationID == null)
                {

                }
                var userDetailsResponse = from s in _context.Registrations where s.RoleID == 1 && s.RegistrationID == RegistrationID select s;
                return PartialView("_UserDetails", userDetailsResponse.FirstOrDefault());
            }
            catch (Exception)
            {
                throw;
            }
        }
    }
}

MarineDataSheet/Controllers/SuperAdminController.cs
using EventApplicationCore.Library;
using MarineDataSheet.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace MarineDataSheet.Controllers
{
    public class SuperAdminController : Controller
    {
        MarineDataEntities md = new MarineDataEntities();

        [HttpGet]
        public ActionResult AssignRoles()
        {
            try
            {
                AssignRolesModel assignRolesModel = new AssignRolesModel();


                List<AdminModel> lstadmin = (from student in md.Registrations
                                             where student.RoleID == 1
                                             select new AdminModel
                                             {
                                                 RegistrationID = student.RegistrationID,
                                                 Name = student.Name
                                             }).ToList();




                List<UserModel> lstunassigned = (from student in md.Usp_GetListofUnAssignedUsers

                                                 select new UserModel
                                                 {
                                                     RegistrationID = student.RegistrationID,
                                                     Name = student.Name
                                                 }).ToList();






                assignRolesModel.ListofAdmins = lstadmin;
                assignRolesModel.ListofUser = lstunassigned;
                return View(assignRolesModel);
            }
            catch (Exception)
            {

                throw;
            }

        }

        [HttpPost]
        public ActionResult AssignRoles(AssignRolesModel objassign)
        {

            try
            {
                if (objassign.ListofUser == null)
                {
                    //TempData["MessageErrorRoles"] = "There are no Users to Assign Roles";
                    //objassign.ListofAdmins = _IAssignRoles.ListofAdmins();
                    //objassign.ListofUser = _IAssignRoles.GetListofUnAssignedUsers();
                    return View(objassign);
                }


                var SelectedCount = (from User in objassign.ListofUser
                                     where User.selectedUsers == true
                                     select User).Count();
                var RegistationId = (from User in objassign.ListofUser
                                     where User.selectedUsers == true
                                     select User.RegistrationID).ToList();

                //var Adminid = (from User in objassign.ListofAdmins
                //                     where User.selectedUsers == true == true
                //                     select User.RegistrationID).FirstOrDefault();

                if (SelectedCount == 0)
                {
                    TempData["MessageErrorRoles"] = "You have not Selected any User to Assign Roles";
                    //objassign.ListofAdmins = _IAssignRoles.ListofAdmins();
                    //objassign.ListofUser = _IAssignRoles.GetListofUnAssignedUsers();
                    return RedirectToAction("AssignRoles");
                }

                if (ModelState.IsValid)
                {
                    for (int i = 0; i < RegistationId.Count(); i++)
                    {
                        AssignedRole asg = new AssignedRole();
                        asg.CreatedBy = Convert.ToInt32(Session["SuperAdmin"]);
                        asg.AssignToAdmin = objassign.RegistrationID;
                        asg.Status = "A";
                        asg.CreatedOn = DateTime.Now;
                        asg.RegistrationID = RegistationId[i];
                        md.Entry(asg).State = EntityState.Added;
                        md.SaveChanges();
                        TempData["MessageRoles"] = "Roles Assigned Successfully!";
                    }

                }
                objassign = new AssignRolesModel();
                //objassign.ListofAdmins = _IAssignRoles.ListofAdmins();
                //objassign.ListofUser = _IAssignRoles.GetListofUnAssignedUsers();

                return RedirectToAction("AssignRoles");
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public ActionResult CreateAdmin()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateAdmin(Registration registration)
        {
            Registration NewUserRegister = new Registration();
            registration.CreatedOn = DateTime.Now;
            if (registration.Password == null || registration.ConfirmPassword == null || registration.Username == null)
            {
                TempData["MessageErrorRegistration"] = "Plese enter the Username and Password";
                return View("CreateAdmin");
            }
            NewUserRegister.Password = EncryptionLibrary.EncryptText(registration.Password);
            NewUserRegister.ConfirmPassword = EncryptionLibrary.EncryptText(registration.ConfirmPassword);
            NewUserRegister.Name = registration.Name;
            NewUserRegister.Mobileno = registration.Mobileno;
            NewUserRegister.EmailID = registration.EmailID;
            NewUserRegister.Gender = registration.Gender;
            NewUserRegister.Birthdate = registration.Birthdate;
            NewUserRegister.DateofJoining = registration.DateofJoining;
            NewUserRegister.Username = registration.Username;
            NewUserRegister.Username = registration.Username;
            NewUserRegister.RoleID = 1; // FOR ADMIN
            md.Registrations.Add(NewUserRegister);
            md.SaveChanges();

            TempData["MessageRegistration"] = "Data Saved Successfully!";

            return View(registration);
        }
    }
}

MarineDataSheet/Views/SuperAdmin/AssignRoles.cshtml
@model MarineDataSheet.Models.AssignRolesModel
@{
    ViewBag.Title = "AssignRoles";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<h4 class="page-header">Assign Roles</h4>

@using (Html.BeginForm())
{
    <div class="panel panel-default">
        <div class="panel-heading">Choose Admin</div>
        <div class="panel-body">

            @if (TempData["MessageRoles"] != null)
            {
                <p class="alert alert-success" id="successMessage">@TempData["MessageRoles"] </p>}

            @if (TempData["MessageErrorRoles"] != null)
            {
                <p class="alert alert-danger" id="successMessage">@TempData["MessageErrorRoles"] </p>}

            @Html.AntiForgeryToken()

            <div class="row">
                <div class="col-md-4">
                    @Html.DropDownListFor(a => a.RegistrationID, new SelectList(Model.ListofAdmins, "RegistrationID", "Name"), new { @class = "form-control" })
                    @Html.ValidationMessageFor(a => a.RegistrationID)
                </div>
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Choose Users To Assign to Admin</div>
        <div class="panel-body">
            <div class="clearfix"></div>
            <div class="row">
                @for (var i = 0; i < Model.ListofUser.Count(); i++)
                {
                    <div class="col-md-4">
                        <div>
                            @Html.CheckBoxFor(it => Model.ListofUser[i].selectedUsers)
                            <label>
                                @Html.DisplayFor(it => Model.ListofUser[i].Name)
                                @Html.HiddenFor(it => Model.ListofUser[i].RegistrationID)
                                @Html.HiddenFor(it => Model.ListofUser[i].Name)
                            </label>
                        </div>
                    </div>}
            </div>
            <br />
            <div class="row">
                <div class="form-group">
                    <div class="col-md-offset-0 col-md-12">
                        <input type="submit" value="Assign Role" class="btn btn-success" />

                        @Html.ActionLink("Cancel", "Dashboard", "SuperAdmin", null, new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
        </div>
    </div>}

MarineDataSheet/Views/SuperAdmin/CreateAdmin.cshtml
@model MarineDataSheet.Registration

@{
    ViewBag.Title = "CreateAdmin";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}

<h4 class="page-header">Create Admin User</h4>

<div class="panel panel-default">
    <div class="panel-heading">Create User</div>
    <div class="panel-body">

        @if (TempData["MessageRegistration"] != null)
        {
            <p class="alert alert-success" id="successMessage">@TempData["MessageRegistration"]</p>}
        @if (TempData["MessageErrorRegistration"] != null)
        {
            <p class="alert alert-danger" id="successMessage">@TempData["MessageErrorRegistration"] </p>}

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="row">
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", @maxlength = 40, @onkeypress = "return onlyspecchar(event);" })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Mobileno, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.TextBoxFor(model => model.Mobileno, new { @class = "form-control", @maxlength = 10, @onkeydown = "return OnlyNumeric(this);" })
                    @Html.ValidationMessageFor(model => model.Mobileno, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.EmailID, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.TextBoxFor(model => model.EmailID, new { @class = "form-control", @maxlength = 50 })
                    @Html.ValidationMessageFor(model => model.EmailID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="row">
                <div class="clearfix"></div>
                <div class="col-lg-4" style="margin-top:20px;">

                    @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.RadioButtonFor(model => model.Gender, "M") @Html.Label("", "Male")
                    @Html.RadioButtonFor(model => model.Gender, "F") @Html.Label("", "Female")
                    <br />
                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Birthdate, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.Birthdate, new { @class = "form-control", @onkeypress = "alert('Choose Birthdate');" })
                    @Html.ValidationMessageFor(model => model.Birthdate, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.DateofJoining, htmlAttributes: new { @class = "control-label" })
                    @Html.TextBoxFor(model => model.DateofJoining, new { @class = "form-control", @onkeypress = "alert('Choose DateofJoining');" })
                    @Html.ValidationMessageFor(model => model.DateofJoining, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.TextBoxFor(model => model.Username, new { @class = "form-control", @maxlength = 20, @onkeypress = "return onlyspecchar(event);", @onblur = "CheckUsernameExists();" })
                    @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.PasswordFor(model => model.Password, new { @class = "form-control", @maxlength = 30, })
                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
                <div class="col-lg-4">
                    @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label manadatory" })
                    @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                </div>
            </div>

            <br />
            <div class="row">
                <div class="col-lg-4">
                    <input type="submit" value="Create Admin" class="btn btn-success" />
                    @Html.ActionLink("Clear", "Registration", "Registration", null, new { @class = "btn btn-danger" })

                    @Html.ActionLink("All Admin", "admin", "AllUsers", null, new { @class = "btn btn-info" })

                </div>
            </div>}

    </div>
</div>




<script type="text/javascript">

    $(document).ready(function () {
        $("#Birthdate").datepicker
            ({
                dateFormat: "yy-mm-dd",
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+100",
                onSelect: function (date) {
                    var dob = new Date(date);
                    var today = new Date();

                    if (dob.getFullYear() + 18 < today.getFullYear()) {

                    }
                    else {
                        $("#Birthdate").val('');
                        alert("You are not eligible for Registration");
                    }
                }
            });

        $("#DateofJoining").datepicker
           ({
               dateFormat: "yy-mm-dd",
               changeMonth: true,
               changeYear: true,
               yearRange: "-100:+100"
           });

    });

    function OnlyNumeric(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        if ((charCode < 48 || charCode > 57)) {
            if (charCode == 8 || charCode == 46 || charCode == 0) {
                return true;
            }
            else {
                return false;
            }
        }
    }

    function CheckUsernameExists() {
        var url = '@Url.Content("~/")' + "Registration/CheckUserNameExists";
        var source = "#Username";
        $.post(url, { Username: $(source).val() }, function (data) {
            if (data) {
                $(source).val('');
                alert("Username Already Used try unique one!");
            }
            else {

            }
        });
    }

    function onlyspecchar(evt) {
        var charCode = (evt.which) ? evt.which : evt.keyCode
        var txt = String.fromCharCode(charCode)
        if ((txt.match(/^[a-zA-Z\b. ]+$/)) || (txt.match(/^[0-9]+$/)) || (charCode == 64) || (charCode == 45) || (charCode == 46) || (charCode == 95) || (charCode == 41)) {
            return true;
        }
        return false;
    }
</script>