MarineDataSheet/Controllers/DataController.cs
using MarineDataSheet.Helpers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using log4net;
using System.Data.Entity;

namespace MarineDataSheet.Controllers
{
    public class DataController : Controller
    {
        MarineDataEntities dc = new MarineDataEntities();
        // GET: Data
        // MarinedataEntities db = new MarinedataEntities();
        private static log4net.ILog Log { get; set; }
        ILog log = log4net.LogManager.GetLogger(typeof(DataController));
        public ActionResult Index()
        {
            log.Info("---Action method in Data Controller was called--");

            return View();
        }

        [HttpPost]
        public ActionResult LoadData()
        {
            //Get parameters
            try
            {
                log.Info("Before Paramater called");

                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var Datasivun_numero = string.Empty;
                var Code = string.Empty;
                var Model = string.Empty;
                var voltage_1 = string.Empty;
                var frequency_1 = string.Empty;
                var Starting_1 = string.Empty;
                var Voltage_2 = string.Empty;
                var frequency_2 = string.Empty;
                var Starting_2 = string.Empty;
                var Barg = string.Empty;
                var Cooling = string.Empty;
                var AmbientTemperature = string.Empty;
                var Yield = string.Empty;

                var datasheet_type = Convert.ToString(Session["datasheettype"]);

                if (Convert.ToString(Session["Laskuri"]) != "")
                {
                     Datasivun_numero = Convert.ToString(Session["Datasivun_numero"]);
                     Code = Convert.ToString(Session["Code"]);
                     Model = Convert.ToString(Session["Model"]);
                     voltage_1 = Convert.ToString(Session["voltage_1"]);
                     frequency_1 = Convert.ToString(Session["frequency_1"]);
                     Starting_1 = Convert.ToString(Session["Starting_1"]);
                     Voltage_2 = Convert.ToString(Session["Voltage_2"]);
                     frequency_2 = Convert.ToString(Session["frequency_2"]);
                     Starting_2 = Convert.ToString(Session["Starting_2"]);
                     Barg = Convert.ToString(Session["Barg"]);
                     Cooling = Convert.ToString(Session["Cooling"]);
                     AmbientTemperature = Convert.ToString(Session["AmbientTemperature"]);
                     Yield = Convert.ToString(Session["Yield"]);

                   
                }
                else
                {
                    Datasivun_numero = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
                    Code = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();
                    Model = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault();
                    voltage_1 = Request.Form.GetValues("columns[4][search][value]").FirstOrDefault();
                    frequency_1 = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault();
                    Starting_1 = Request.Form.GetValues("columns[6][search][value]").FirstOrDefault();
                    Voltage_2 = Request.Form.GetValues("columns[7][search][value]").FirstOrDefault();
                    frequency_2 = Request.Form.GetValues("columns[8][search][value]").FirstOrDefault();
                    Starting_2 = Request.Form.GetValues("columns[9][search][value]").FirstOrDefault();
                    Barg = Request.Form.GetValues("columns[10][search][value]").FirstOrDefault();
                    Cooling = Request.Form.GetValues("columns[11][search][value]").FirstOrDefault();
                    AmbientTemperature = Request.Form.GetValues("columns[12][search][value]").FirstOrDefault();
                    Yield = Request.Form.GetValues("columns[13][search][value]").FirstOrDefault().ToString();

                    Session["Model"] = Model;
                    Session["Code"] = Code;
                    Session["voltage_1"] = voltage_1;
                    Session["frequency_1"] = frequency_1;
                    Session["Starting_1"] = Starting_1;
                    Session["Voltage_2"] = Voltage_2;
                    Session["frequency_2"] = frequency_2;
                    Session["Starting_2"] = Starting_2;
                    Session["Barg"] = Barg;
                    Session["Cooling"] = Cooling;
                    Session["AmbientTemperature"] = AmbientTemperature;
                    Session["Yield"] = Yield;
                    Session["Datasivun_numero"] = Datasivun_numero;

                }
                //Get Sort columns value
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecords = 0;
                log.Info("ActionMethod was Called Before Database");
                using (MarineDataEntities dc = new MarineDataEntities())
                {
                    var dv = (from a in dc.Data where (a.Datasheet_status == "In Use") select a);

                    //Sorting
                    if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                    {
                        dv = dv.OrderBy(sortColumn + " " + "desc");

                    }
                    if (!string.IsNullOrEmpty(searchValue))
                    {
                        dv = dv.Where(m => m.Datasivun_numero.Contains(searchValue) || m.Code.Contains(searchValue) || m.Model_No.Contains(searchValue));
                    }
                    if (!string.IsNullOrEmpty(Datasivun_numero))
                    {
                        dv = dv.Where(m => m.Datasivun_numero.Contains(Datasivun_numero));
                    }
                    if (!string.IsNullOrEmpty(Code))
                    {
                        dv = dv.Where(m => m.Code.Equals(Code) || m.Code.Contains(Code));
                    }
                    if (!string.IsNullOrEmpty(Model))
                    {
                        Session[Model] = Model;
                        dv = dv.Where(m => m.Model_No.Contains(Model) || m.Model_No.Equals(Model));
                    }
                    if (!string.IsNullOrEmpty(voltage_1))
                    {
                        dv = dv.Where(m => m.C1_Voltage.Equals(voltage_1) || m.C1_Voltage.Contains(voltage_1));
                    }
                    if (!string.IsNullOrEmpty(frequency_1))
                    {
                        dv = dv.Where(m => m.C1_Frequency.Equals(frequency_1) || m.C1_Frequency.Contains(frequency_1));
                    }
                    if (!string.IsNullOrEmpty(Starting_1))
                    {
                        dv = dv.Where(m => m.C1_Starting_type.Equals(Starting_1) || m.C1_Starting_type.Contains(Starting_1));
                    }
                    if (!string.IsNullOrEmpty(Voltage_2))
                    {
                        dv = dv.Where(m => m.C2_Voltage.Equals(Voltage_2) || m.C2_Voltage.Contains(Voltage_2));
                    }
                    if (!string.IsNullOrEmpty(frequency_2))
                    {
                        dv = dv.Where(m => m.C2_Frequency.Equals(frequency_2) || m.C2_Frequency.Contains(frequency_2));
                    }
                    if (!string.IsNullOrEmpty(Starting_2))
                    {
                        dv = dv.Where(m => m.C2_Starting_type.Equals(Starting_2) || m.C2_Starting_type.Contains(Starting_2));
                    }
                    if (!string.IsNullOrEmpty(Barg))
                    {
                        dv = dv.Where(m => m.Maximum_working_pressure_barg.ToString().Contains(Barg) || m.Maximum_working_pressure_barg.ToString().Equals(Barg));
                    }
                    if (!string.IsNullOrEmpty(Cooling))
                    {
                        dv = dv.Where(m => m.Cooling.Equals(Cooling) || m.Cooling.Contains(Cooling));
                    }
                    if (!string.IsNullOrEmpty(AmbientTemperature))
                    {
                        dv = dv.Where(m => m.Maximum_ambient_temperature_C.ToString().Contains(AmbientTemperature) || m.Maximum_ambient_temperature_C.ToString().Equals(AmbientTemperature));
                    }
                    if (!string.IsNullOrEmpty(Yield))
                    {
                        dv = dv.Where(m => m.Capacity_at_normal_working_pressure_m_min.ToString().Contains(Yield) || m.Capacity_at_normal_working_pressure_m_min.ToString().Equals(Yield));
                    }
                    if (Session["Laskuri"] != null)
                    {
                        string type = Convert.ToString(Session["datasheettype"]);
                        dv = dv.Where(x => x.Model_No.Contains(Model) ||
                        x.Code.Contains(Code) ||
                        x.C1_Voltage.Contains(voltage_1) ||
                        x.C1_Frequency.Contains(frequency_1) ||
                        x.C1_Starting_type.Contains(Starting_1) ||
                        x.C2_Voltage.Contains(Voltage_2) ||
                        x.C2_Frequency.Contains(frequency_2) ||

MarineDataSheet/Controllers/ViewDataSheetController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Linq.Dynamic;
using log4net;
using MarineDataSheet.Helpers;
using Rotativa.MVC;

namespace MarineDataSheet.Controllers
{
    public class ViewDataSheetController : Controller
    {
        MarineDataEntities md = new MarineDataEntities();
        private static log4net.ILog Log { get; set; }
        ILog log = log4net.LogManager.GetLogger(typeof(DataController));
        // GET: ViewDataSheet
        public ActionResult Index()
        {
            log.Info("---Action method in Data Controller was called--");

            return View();
        }
        [HttpPost]
        public ActionResult LoadData()
        {
            //Get parameters
            try
            {
                log.Info("Before Paramater called");

                var draw = Request.Form.GetValues("draw").FirstOrDefault();
                var start = Request.Form.GetValues("start").FirstOrDefault();
                var length = Request.Form.GetValues("length").FirstOrDefault();
                var Datasivun_numero = Request.Form.GetValues("columns[1][search][value]").FirstOrDefault();
                var Revision = Request.Form.GetValues("columns[2][search][value]").FirstOrDefault();
                var Code = Request.Form.GetValues("columns[3][search][value]").FirstOrDefault();
                var Model = Request.Form.GetValues("columns[4][search][value]").FirstOrDefault();
                var Barg = Request.Form.GetValues("columns[5][search][value]").FirstOrDefault();
                var notes = Request.Form.GetValues("columns[6][search][value]").FirstOrDefault();
                var Enigneering_notes = Request.Form.GetValues("columns[7][search][value]").FirstOrDefault();
                //Get Sort columns value
                var sortColumn = Request.Form.GetValues("columns[" + Request.Form.GetValues("order[0][column]").FirstOrDefault() + "][name]").FirstOrDefault();
                var sortColumnDir = Request.Form.GetValues("order[0][dir]").FirstOrDefault();
                var searchValue = Request.Form.GetValues("search[value]").FirstOrDefault();
                int pageSize = length != null ? Convert.ToInt32(length) : 0;
                int skip = start != null ? Convert.ToInt32(start) : 0;
                int totalRecords = 0;
                log.Info("ActionMethod was Called Before Database");
                using (MarineDataEntities dc = new MarineDataEntities())
                {
                    var dv = (from a in dc.Data where (a.Datasheet_status == "In Use") select a);
                    //Sorting
                    if (!(string.IsNullOrEmpty(sortColumn) && string.IsNullOrEmpty(sortColumnDir)))
                    {
                        dv = dv.OrderBy(sortColumn + " " + sortColumnDir);

                    }
                    if (!string.IsNullOrEmpty(searchValue))
                    {
                        dv = dv.Where(m => m.Datasivun_numero.Contains(searchValue) || m.Code.Contains(searchValue) || m.Model_No.Contains(searchValue));
                    }
                    else if (!string.IsNullOrEmpty(Datasivun_numero))
                    {
                        dv = dv.Where(m => m.Datasivun_numero.Contains(Datasivun_numero));
                    }
                    else if (!string.IsNullOrEmpty(Revision))
                    {
                        dv = dv.Where(m => m.Datasheet_revision.Contains(Revision));
                    }
                    else if (!string.IsNullOrEmpty(Code))
                    {
                        dv = dv.Where(m => m.Code.Contains(Code));
                    }
                    else if (!string.IsNullOrEmpty(Model))
                    {
                        dv = dv.Where(m => m.Model_No.Contains(Model));
                    }
                    else if (!string.IsNullOrEmpty(Barg))
                    {
                        dv = dv.Where(m => m.Maximum_working_pressure_barg.ToString().Contains(Barg));
                    }
                    else if (!string.IsNullOrEmpty(notes))
                    {
                        dv = dv.Where(m => m.Lisätietoja.ToString().Contains(notes));
                    }
                    else if (!string.IsNullOrEmpty(Enigneering_notes))
                    {
                        dv = dv.Where(m => m.Suunnittelun_kommentit.ToString().Contains(Enigneering_notes));
                    }
                    totalRecords = dv.Count();
                    var data = dv.Skip(skip).Take(pageSize).ToList();
                    return Json(new { draw = draw, recordsFiltered = totalRecords, recordsTotal = totalRecords, data = data }, JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                log.Error(ex.Message.ToString());
                throw ex;
            }
            // get Start (paging start index) and length (page size for paging)

        }
    }
}

MarineDataSheet/Views/Data/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutSuperAdmin.cshtml";
}
<link href="~/Scripts/dataTablesScripts/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="~/Scripts/dataTablesScripts/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/dataTablesScripts/jquery.dataTables.min.js"></script>
<script src="~/Scripts/dataTablesScripts/dataTables.bootstrap4.min.js"></script>


<style type="text/css">
    .toolbar {
        float: left;
    }

    #scrolly {
        width: 1000px;
        height: 450px;
        overflow: auto;
        overflow-y: hidden;
        margin: 0 auto;
        white-space: nowrap;
    }
</style>
@using (Html.BeginForm("MoveNotInUse", "Data", FormMethod.Post))
{
    if (TempData["MessageModifyDataSheet"] != null)
        {
            <p class="alert alert-success" id="successMessage">@TempData["MessageModifyDataSheet"]</p>
        }
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Data Sheet List</div>
                <div class="text-right">
                    <button type="submit" id="btbmovenotinuse" value="Delete" class="btn btn-sm btn-danger rounded-0" onclick="return confirm('Are you sure?')"><i class="fa fa-trash-o"></i> Move To Not In-Use</button>

                </div>

                <div class="panel-body">

                    <table id="myTable" class="table table-striped table-bordered dt-responsive table-hover" width="100%" cellspacing="0">

                        <thead>
                            <tr>

                                <th>ID</th>
                                <th>Datasheet Number</th>
                                <th>Code</th>
                                <th>Model</th>
                                <th>Voltage</th>
                                <th>Frequency</th>
                                <th>Starting method</th>
                                <th>Voltage</th>
                                <th>Frequency</th>
                                <th>Starting method</th>
                                <th>Barg</th>
                                <th>Cooling</th>
                                <th>C°</th>
                                <th>Yield</th>
                                <th>View Details</th>

                            </tr>
                        </thead>
                        <tbody id="tblData"></tbody>
                        <tfoot>
                            <tr>

                                <th>ID</th>
                                <th>Datasheet No</th>
                                <th>Code</th>
                                <th>Model</th>
                                <th>1.Voltage</th>
                                <th>1.Frequency</th>
                                <th>1.Starting method</th>
                                <th>2.Voltage</th>
                                <th>2.Frequency</th>
                                <th>2.Starting method</th>
                                <th>Barg</th>
                                <th>Cooling</th>
                                <th>C°</th>
                                <th>Air Delivery</th>
                                <th>View Download</th>

                            </tr>
                        </tfoot>
                    </table>
                </div>

            </div>
        </div>
    </div>
}


<script>

    $(document).ready(function () {
        $("#btbmovenotinuse").attr("disabled", "disabled");

        var datatableinstance = $("#myTable").DataTable({

           
            "processing": true, // for show progress bar
            "language": {
                processing: '<i class="fa fa-spinner fa-spin fa-3x fa-fw"></i><span class="sr-only">Loading...</span> '
            },   
            
            "serverSide": true, // for process server side
            "filter": true, // this is for disable filter (search box)
            "orderMulti": false, // for disable multiple column at once
            "search": true,
            "searchable": true,
            "lengthMenu": [[100, 200, 500], [100, 200, 500]],
            "ajax": {
                "url": "/data/LoadData",
                "type": "POST",
                "datatype": "json"
            },
        
            "columnDefs":
                [{
                    "targets": [0],
                    "visible": false,
                    "searchable": false,

                },


                {
                    "targets": [14],
                    "visible": true,
                    "searchable": false,
                    "orderable": false

                },

                ],
            "columns": [
                { "data": "Laskuri", "name": "Laskuri", "autoWidth": true },
                { "data": "Datasivun_numero", "name": "Datasivun_numero", "autoWidth": true },
                { "data": "Code", "name": "Code", "autoWidth": true },
                { "data": "Model_No", "name": "Model_No", "autoWidth": true },
                { "data": "C1_Voltage", "name": "C1_Voltage", "autoWidth": true },
                { "data": "C1_Frequency", "name": "C1_Frequency", "autoWidth": true },
                { "data": "C1_Starting_type", "name": "C1_Starting_type", "autoWidth": true },
                { "data": "C2_Voltage", "name": "C2_Voltage", "autoWidth": true },
                { "data": "C2_Frequency", "name": "C2_Frequency", "autoWidth": true },
                { "data": "C2_Starting_type", "name": "C2_Starting_type", "autoWidth": true },
                { "data": "Maximum_working_pressure_barg", "name": "Maximum_working_pressure_barg", "autoWidth": true },
                { "data": "Cooling", "name": "Cooling", "autoWidth": true },
                { "data": "Maximum_ambient_temperature_C", "name": "Maximum_ambient_temperature_C", "autoWidth": true },
               /* { "data": "Capacity_at_normal_working_pressure_m_min", "name": "Capacity_at_normal_working_pressure_m_min", "autoWidth": true },*/
                { "data": "Capacity_at_normal_working_pressure_m_min", render: $.fn.dataTable.render.number('', '.', 2, '') },

                {
                    "render": function (data, type, full, meta) {

                        return "<i class='glyphicon glyphicon-file' data-toggle='tooltip' title='View DataSheet' onclick=ShowUserDetails('" + full.Laskuri + "')></i>&nbsp;" +
                            "<i class='fa fa-file-pdf-o' data-toggle='tooltip' title='Print PDF' onclick=Print('" + full.Laskuri + "')></i>&nbsp;" +
                            "<i class='fa fa-file-word-o' data-toggle='tooltip' title='Print Doc' onclick=PrintDoc('" + full.Laskuri + "')></i>&nbsp;" +
                            "<input type='checkbox' id='chctxtid' name='ID' value='" + full.Laskuri + "' onclick=GetSelected('" + full.Laskuri + "');></input>";
                    }
                }
            ]


        });



        $("#myTable thead th").each(function () {
            var Title = $('#myTable tfoot th').eq($(this).index()).text();
            $(this).html('<input id="txtsearch" type="text" class="form-control" size="7px;" placeholder="' + Title + '"/>');

        });
        datatableinstance.columns().every(function () {
            var datatablecolum = this;
            var SearchTexBoxes = $(this.header()).find('input');
            SearchTexBoxes.on('keyup change', function () {
                datatablecolum.search(this.value).draw();
            });
            SearchTexBoxes.on('click', function (e) {

                e.stopPropagation();
            })
        });

      

    });

</script>
<script type="text/javascript">
    function ShowUserDetails(ID) {
        var url = '@Url.Content("~/")' + "Data/ViewDatasheet/"+ ID;
        $.ajax({
            type: "POST",
            url: url,
            data: '{Laskuri: "' + ID + '" }',
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response)
            {
                window.location.href = url;
                //$('#contentBody').html(response);
                //$('#myModal').modal('show');
            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        });
    }
    function Print(ID) {
        var url = '@Url.Content("~/")' + "ExportDatasheet/Print/"+ ID;
        $.ajax({
            type: "POST",
            //url: url,
            data: '{Laskuri: "' + ID + '" }',
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response)
            {
                window.open(url);
            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        });
    }
    function PrintDoc(ID) {
         var url = '@Url.Content("~/")' + "ExportDatasheet/Export/"+ ID;
        $.ajax({
            type: "POST",
            //url: url,
            data: '{Laskuri: "' + ID + '" }',
            contentType: "application/json; charset=utf-8",
            dataType: "html",
            success: function (response)
            {
                window.open(url);
            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        });
    }
    function GetSelected(ID) {
        //Create an Array.
        var selected = new Array();

        //Reference the Table.
        var tblFruits = document.getElementById("myTable");

        //Reference all the CheckBoxes in Table.
        var chks = tblFruits.getElementsByTagName("input");

        // Loop and push the checked CheckBox value in Array.
        for (var i = 0; i < chks.length; i++) {
            if (chks[i].checked) {

                selected.push(ID);
            }
        }

        //Display the selected CheckBox values.
        if (selected.length > 0) {
            $('#btbmovenotinuse').prop('disabled', false);
        }

    };
</script>



@*<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">

                @Html.ActionLink("Close", "Index", "Data", null, new { @class = "btn btn-info" })
            </div>
            <div class="modal-body" id="contentBody">
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Close", "Index", "Data", null, new { @class = "btn btn-info" })
            </div>
        </div>
    </div>
</div>*@